### ISSUE TITLE
Adafruit BMP280 lib

### ISSUE THREAD

**Issue by bastienwirtz** [cudacode/Python-BMP280#1]
Hey, 

A working version is available here https://github.com/bastienwirtz/Adafruit_Python_BMP/blob/master/Adafruit_BMP/BMP280.py :)

**Comment by pdp7** [comment]
@bastienwirtz thanks!

**Comment by daverck** [comment]
Hi,

The specified version work with i2c.
Does someone have a solution working with spi for the raspberry ?
